### ISSUE TITLE
cannot install via pip on macOS 10.14 Mojave

### ISSUE THREAD

**Issue by fangchenli** [tobywf/pasteboard#11]
In https://github.com/pandas-dev/pandas/pull/40101, we found that `pasteboard` cannot be installed via pip on macOS 10.14 Mojave. 

It causes `ERROR: Could not build wheels for pasteboard which use PEP 517 and cannot be installed directly`. See https://dev.azure.com/pandas-dev/pandas/_build/results?buildId=55179&view=logs&j=b516280a-8c75-541b-8ba0-ae13561718a7&t=a9217cb1-24f6-5625-717d-72085a70e1d3&l=394 for detail.

But it works on macOS 10.15 Catalina.

**Comment by tobywf** [comment]
Your log clearly describes why:
```
  src/pasteboard/pasteboard.m:267:33: error: 'NSPasteboardTypeFileURL' is only available on macOS 10.13 or newer [-Werror,-Wunguarded-availability-new]
      NSArray *supportedTypes = @[NSPasteboardTypeFileURL];
                                  ^~~~~~~~~~~~~~~~~~~~~~~
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:38:38: note: 'NSPasteboardTypeFileURL' has been marked as being introduced in macOS 10.13 here, but the deployment target is macOS 10.9.0
  APPKIT_EXTERN NSPasteboardType const NSPasteboardTypeFileURL                    NS_AVAILABLE_MAC(10_13); // Equivalent to kUTTypeFileURL
                                       ^
  src/pasteboard/pasteboard.m:267:33: note: enclose 'NSPasteboardTypeFileURL' in an @available check to silence this warning
      NSArray *supportedTypes = @[NSPasteboardTypeFileURL];
                                  ^~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
```
It looks to me the deployment target is set to 10.9 in your build environment, I think this is set via `MACOSX_DEPLOYMENT_TARGET`. AFAIK, the only versions supported by Apple are 10.14 and above. Building wheels for 10.9 compatibility seems a bit pointless.

Unfortunately, for providing pre-build wheels, I'm limited by [which environments are provided by GitHub actions](https://docs.github.com/en/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources), which doesn't include Mojave.

Edit: If you absolutely can't change your build environment/need to support older versions *and* don't need File URL support (copying file paths from the pasteboard), I'd also be willing to accept a PR or work with you to disable that functionality sensibly.

**Comment by fangchenli** [comment]
Thank you for this explanation! We currently run macOS build on Azure using 10.14. I'll discuss with others in the team to see what's the best solution.
